# Generated by Django 3.2.7 on 2022-07-21 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
