# Generated by Django 3.2.7 on 2022-07-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('disapproved', 'disapproved')], default='pending', max_length=11),
        ),
    ]
