# Generated by Django 3.2.7 on 2022-04-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('disapproved', 'disapproved')], default='dissaproved', max_length=11),
        ),
    ]
