# Generated by Django 3.2.7 on 2022-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('disapproved', 'disapproved')], default='disapproved', max_length=11),
        ),
    ]
