# Generated by Django 3.2.7 on 2022-07-30 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('disapproved', 'disapproved')], default='pending', max_length=11)),
                ('question', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('p', 'politics'), ('s', 'sports'), ('g', 'gaming'), ('h', 'health'), ('m', 'music')], default='', max_length=10)),
                ('answer1', models.CharField(blank=True, max_length=200, null=True)),
                ('count1', models.IntegerField(default=0)),
                ('answer2', models.CharField(blank=True, max_length=200, null=True)),
                ('count2', models.IntegerField(default=0)),
                ('answer3', models.CharField(blank=True, max_length=200, null=True)),
                ('count3', models.IntegerField(default=0)),
                ('answer4', models.CharField(blank=True, max_length=200, null=True)),
                ('count4', models.IntegerField(default=0)),
                ('answer5', models.CharField(blank=True, max_length=200, null=True)),
                ('count5', models.IntegerField(default=0)),
                ('answer6', models.CharField(blank=True, max_length=200, null=True)),
                ('count6', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('started_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('profile_picture_number', models.CharField(choices=[("['1']", '1'), ("['2']", '2'), ("['3']", '3'), ("['4']", '4'), ("['5']", '5'), ("['6']", '6')], max_length=10)),
                ('cover_picture_number', models.CharField(default=3, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='voted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_polls', to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='poll_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_str', models.CharField(default='empty', max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_polls', to='polls.user')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_polls', to='polls.user')),
            ],
        ),
    ]
