# Generated by Django 3.2.7 on 2022-01-01 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('p', 'politics'), ('s', 'sports'), ('g', 'gaming'), ('h', 'health'), ('a', 'anime')], default='', max_length=10)),
                ('answer1', models.CharField(blank=True, max_length=200, null=True)),
                ('count1', models.IntegerField(default=0)),
                ('answer2', models.CharField(blank=True, max_length=200, null=True)),
                ('count2', models.IntegerField(default=0)),
                ('answer3', models.CharField(blank=True, max_length=200, null=True)),
                ('count3', models.IntegerField(default=0)),
                ('answer4', models.CharField(blank=True, max_length=200, null=True)),
                ('count4', models.IntegerField(default=0)),
                ('answer5', models.CharField(blank=True, max_length=200, null=True)),
                ('count5', models.IntegerField(default=0)),
                ('answer6', models.CharField(blank=True, max_length=200, null=True)),
                ('count6', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('started_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='voted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
    ]
