# Generated by Django 3.2.7 on 2022-07-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_number',
            field=models.CharField(choices=[("['1']", '1'), ("['2']", '2'), ("['3']", '3'), ("['4']", '4'), ("['5']", '5'), ("['6']", '6')], max_length=10),
        ),
    ]
