# Generated by Django 3.2.7 on 2022-07-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='genre',
            field=models.CharField(choices=[('p', 'politics'), ('s', 'sports'), ('g', 'gaming'), ('h', 'health'), ('m', 'music')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_picture_number',
            field=models.IntegerField(default=3),
        ),
    ]
