# Generated by Django 3.2.7 on 2022-07-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_user_profile_picture_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture_number',
            field=models.CharField(default=3, max_length=10),
        ),
    ]
