# Generated by Django 3.2.7 on 2022-07-21 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_cover_picture_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
