# Generated by Django 3.2.7 on 2022-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='creator',
            field=models.CharField(default='wissem', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
