# Generated by Django 3.2.7 on 2022-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='genre',
            field=models.CharField(choices=[('p', 'politics'), ('s', 'sports'), ('g', 'gaming'), ('h', 'health'), ('m', 'music')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=80),
        ),
    ]
