# Generated by Django 4.0 on 2022-01-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=255, unique=True),
        ),
    ]
