# Generated by Django 4.0 on 2022-01-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_name_user_username_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='voted',
            name='choice',
            field=models.IntegerField(default=0),
        ),
    ]
