# Generated by Django 4.0 on 2022-01-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_voted_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=255),
        ),
    ]
